Azure Pipelines build fix
For some reason, build task in build pipeline reporting error CS8602
on `AzureSmtpClient` (line 29) and `DefaultSmtpClient` (line 28),
causing build failure.